server:
  port: 6060
spring:
  application:
    name: report-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_report?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
#    url: jdbc:mysql://localhost:3306/ecommerce_report?useSSL=false&allowPublicKeyRetrieval=true
#    url: {SPRING_DATASOURCE_URL}
#    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ecommerce_report?useSSL=false&allowPublicKeyRetrieval=true}
#    username: ${SPRING_DATASOURCE_USERNAME:root}
#    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

#    Flyway will create the table â€” NOT Hibernate.
#    Because Flyway runs before Hibernate during startup.
#
#    ðŸ‘‰ Hibernate will see the table already existing and will not try to recreate or drop it, even if ddl-auto=update.

cloud:
  aws:
    credentials:
      access-key: test               # LocalStack test key
      secret-key: test               # LocalStack test secret
    region:
      static: ap-south-1
    s3:
      endpoint: http://localhost:4566       # LocalStack endpoint
      path-style-access-enabled: true       # REQUIRED for LocalStack

app:
  bucket-name: spring-bucket        # Your S3 bucket created via spring app
  #bucket-name: terraform-demo-bucket        # Your S3 bucket created via Terraform
