apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-report-service.fullname" . }}
  labels:
    {{- include "helm-report-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-report-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-report-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- if .Values.profile }}
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.profile }}"
            {{- end }}
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.spring.datasource.url }}"
            - name: SPRING_DATASOURCE_USERNAME
              value: "{{ .Values.spring.datasource.username }}"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "{{ .Values.spring.datasource.password }}"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "{{ .Values.jpa.hibernateDdlAuto }}"
            - name: SPRING_FLYWAY_ENABLED
              value: "{{ .Values.flyway.enabled }}"
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              value: "{{ .Values.flyway.baselineOnMigrate }}"
