apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-report-service.fullname" . }}
  labels:
    {{- include "helm-report-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
  selector:
    {{- include "helm-report-service.selectorLabels" . | nindent 4 }}
